### ISSUE TITLE
Create a summary file to bulk annotate OpenNeuro pheno data

### ISSUE THREAD

**Issue by surchs** [neurobagel/bulk_annotations#1]
We need a file / format that for a given list of OpenNeuro / datalad BIDS datasets
- lists each column of participants.tsv (with description from .json if available)
- lists the discrete values
- has a column where we can enter controlled term IRIs to signify that the col/val combo should be mapped to this term

So that we can go and bulk annotate OpenNeuro datasets without having to repeat a process on a per dataset level.

Tasks we probably need to do:
  - [x] Create a script that can get and process a number of ON datasets
  - [x] Get as little data as possible (e.g. use datalad)
  - [x] Find the `participants.tsv` file in each dataset (and `participants.json` if available)
  - [ ] Do some basic filtering on these files to exclude bad data / data we don't like
  - [ ] At first create a spreadsheet that allows us to manually annotate:
    - dataset ID
    - column name 
    - column description (if available)
    - data type of each column

This should help us do a first sort of columns we want to annotate further, ignore

---

In a second time we may want to extend this spreadsheet to:
    - identify discrete variables and show unique elements
    - add a column for controlled terms (this is where annotation should go)
    - identify continuous variables (only age, exclude non-age columns - or transform if feeling generous)

This could probably be tackled in separate issue / PR.

Something like this would be helpful:

| dataset | column         | value | is_row | description                   | controlled_term  |
|---------|----------------|-------|--------|-------------------------------|------------------|
| ds001   | participant_id | ""    | 1      | ""                            | nb:ParticipantID |
| ds001   | sex            |       | 1      | "Sex reported by participant" | nb:Sex           |
| ds001   | sex            | 1     | 0      | "Male"                        | snomed:Male      |
| ds001   | sex            | 2     | 0      | "Female"                      | snomed:Female    |
| ds001   | sex            | " "   | 0      | ""                            | nb:MissingValue  |
| ds001   | age            |       | 1      | "Age of participant"          | nb:Age           |
| ds002   | ...            | ...   | ...    |                               | ...              |

The idea is that a human annotator can go and add controlled term mappings in the `controlled_term` column.
The idea of `is_row` is to allow us to say what a specific column in the `participants.tsv` file is "about", before we then
go and look at each unique value inside of this column (provided the column is about a discrete variable) and annotate each value as well.

**Comment by Remi-Gau** [comment]
@surchs 
would something like this help: https://github.com/Remi-Gau/list_openneuro_derivatives/blob/main/openneuro.tsv

**Comment by surchs** [comment]
Yes, that looks perfect. Thanks! :tada:

**Comment by surchs** [comment]
Since Remi has already done 95% of this issue, I'll just keep it as one thing here.

**Comment by Remi-Gau** [comment]
One thing I can do is create a mini-openneuro where I have one folder per dataset with only the participants.tsv and participants.json of each dataset.

Would this help.

This could even be a git repo.

**Comment by surchs** [comment]
You mean like a big single repo with all of these guys: https://github.com/OpenNeuroDatasets?

**Comment by surchs** [comment]
@Remi-Gau coud you take a look at the example of a "annotation-tsv" I added above and see if the issue is clear enough now to be worked on? If so, you can move it to Spec-done.

**Comment by Remi-Gau** [comment]
OK I think I get it.

Note that I will likely add an extra column to dump the content of the participants.json if there is one: for example for the description of a column or of a level.

**Comment by Remi-Gau** [comment]
@surchs 
I think I may need to meet with you and whoever else is interested on this one because it seems that those 2 points are not as trivial as they sound.

- identify discrete variables and show unique elements
- identify continuous variables (only age, exclude non-age columns - or transform if feeling generous)

I am happy to spend more time on this but before I do I would prefer to check in with the rest of you

**Comment by Remi-Gau** [comment]
following discussion today it may be worth as a first pass to make just an "inventory" of all the columns available in each participants.tsv.

@surchs 
Does that mean a respec of the top message of this issue?

**Comment by surchs** [comment]
Yes please! We try to keep the description up to date as we figure out the issue!

**Comment by Remi-Gau** [comment]
@surchs 
most of this got done by #6 but there are a few things left.
should I just close this issue and open a new one to go directly in specify active?

**Comment by surchs** [comment]
thanks for clarifying!
