### ISSUE TITLE
Annotate four representative OpenNeuro datasets

### ISSUE THREAD

**Issue by surchs** [neurobagel/bulk_annotations#10]
Good datasets are:

- [x] ds000115
- [x] ds000144
- [x] ds000201
- [x] ds003770

Here is the main [GDrive spreadsheet](https://docs.google.com/spreadsheets/d/1_6dnAjl2B2xse3uEB9UgKQziZeduZ9MDAVtUPW5IwIY/edit?usp=sharing) with all datasets.

To complete:

- [x] Annotate or exclude each level
- [x] Make ~~a copy~~ edit: a new sheet of the original .tsv in https://github.com/neurobagel/bulk_annotations/issues/2 so that we can use these data for further processing
- [x] document any relevant things in this issue.

For reviewer: please take a look at the document and see if you have any notes on how we could make this easier to parse.

**Comment by surchs** [comment]
Things noticed while annotating, just collecting for now:

Missing conditions. `ds000115` has a `condit` column with what looks like clinical conditions. There are levels in there that we cannot model, but we want to model the other levels. Example:
- `SCZ-SIB` -> probably sibling with schizophrenia -> cannot model
- `SCZ` -> probably participant with schizophrenia -> we can model
So what do I do about the things we can't model? Our constraints are:
- need to map every unique level in diagnosis column to controlled term, or
- mark the level as "missing value"
If those are my only options, I need to label this as "missing". Which is clearly wrong.
So we probably want to have another category for "cannot model" or otherwise rethink our annotation approach.

**Comment by surchs** [comment]
OK, I think this thing is done. Overall summary:
- we need to figure out a way to expand some numerical columns when they are used to designate categorical stuff (e.g. diagnoses). presence of a data dictionary with a "Levels" key might be sufficient signal for now
- there is a pretty large percentage of assessment tools I could not model (even just for 4 datasets) because Cognitive Atlas doesn't have it. Some of these assessments are in SNOMED, but not all of them. So we'll have to think about what we want to do here.

**Comment by jarmoza** [comment]
>measurement that isn't a tool. For example: ds000201 has BMI1 for Body Mass Index on session 1. Cool. But cogatlas doesn't have that. Makes sense, it's not a tool. More like "heart rate" or "height". Still, something we'd probably like to annotate. So what should we do with these things? SNOMED has them, but then we mix vocabularies...

missing terms. For assessment tools, there are things that exist in the real world, are assessments, but don't exist in cognitive atlas. Example: ds000201 has HADS_Anxiety which is the "Hospital Anxiety and Depression scale, Anxiety subscale". I can find that in SNOMED: snomed:273524006, even down to the subscale. Hhmm...

I had assumed we were going to be mixing vocabularies anyway...

>clashing abbreviations. Not sure if this is a real problem. But I was looking for the "Beck Depression Inventory" in cognitive-atlas. They don't have it. They do have a "BDI" (the common abbreviation), but it refers to "battelle developmental inventory" - no idea what that is. I guess the main observation here is: we need to pay attention to how we let our users search for terms, because they might have a hard time finding the right term if the vocabulary isn't doing a great job with explicit names / abbreviations.

This might point to the need to have controlled vocabulary term metadata on display to help guide the user

**Comment by surchs** [comment]
> I had assumed we were going to be mixing vocabularies anyway...

No. We have two principles so far: 
1. Make it easy to use
2. Tell people what vocabulary to pick values from

There may be some cases now where we are not being consistent about 2 (e.g. healty-controls currently comes from NCIT rather than SNOMED). But that's one of the "lessons learned" from the OMOP folks that we should really stick with: one vocabulary per variable.

**Comment by surchs** [comment]
> This might point to the need to have controlled vocabulary term metadata on display to help guide the user

Yeah. It might not be enough to just show the name in a dropdown. Maybe we need, as you say, other metadata. 
Let's see. I could imagine that this can get quite complex quickly.

**Comment by alyssadai** [comment]
Moving into Review - Active, I'll take a look at the tsv as well 🙂

**Comment by surchs** [comment]
Thanks for your comments @alyssadai! I agree, we should discuss each of these. I'll link this conversation on the internal wiki to keep a record and then move some of these points over there: https://github.com/neurobagel/documentation/wiki/Neurobagel-Data-Model-limitations
