### ISSUE TITLE
[BUG] Numeric levels are not expanded

### ISSUE THREAD

**Issue by surchs** [neurobagel/bulk_annotations#11]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Expected Behavior

in OpenNeuro `ds000144` I have `SADDx_p` encoding presence of social anxiety.
[From the data dictionary](https://openneuro.org/datasets/ds000144/versions/00002/file-display/participants.json) I can see that it is encoded as
- 0: Not Meeting Criteria for SAD at Preschool
- 1: Meeting Criteria for SAD at Preschool

I would like to see both unique values (or any others I haven't seen) in in the .tsv, 
so that I can annotate the value itself with a controlled term.
E.g. here it would be

1 = `<Social Anxiety Disorder>`

### Current Behavior

I just see the row name in the .tsv. Probably because the data type of the row is numeric
(int64 in this case)

### Anything else?

This came up in https://github.com/neurobagel/bulk_annotations/issues/10

So one fix would be to handle it as a categorical variable on account of the Levels key in the data dictionary. If the data dictionary was incomplete or missing, we would have to find another way to address this.

**Comment by surchs** [comment]
@Remi-Gau can you take a look at this and tell me if this is clear. An example of this is row 541 in https://docs.google.com/spreadsheets/d/1dsMt4nUbD_EI07jCUUbczFEliyLYoaBVaR2Pz5fsIpw/edit#gid=288587227

**Comment by Remi-Gau** [comment]
OK will send a PR to fix.
