### ISSUE TITLE
Bulk data dictionaries currently missing type annotations (`Transformation`) for age

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bulk_annotations#17]
- if column is about `age`
  - check the `type` column
  - if it is one of the recognized transform heuristics -> apply that
  - if not -> try to see if we can guess it 
  - if still not -> log.warning and skip column

and make sure that:
- [x] given an isabout age and a valid type -> I get the correct annotation out
- [x] given isabout age and nonsense type -> I don't have any Neurobagel annotations in the output
- [x] if no isabout age: do not add any transformation stuff

**Comment by surchs** [comment]
proposed solution: 

- go back to https://docs.google.com/spreadsheets/d/1_6dnAjl2B2xse3uEB9UgKQziZeduZ9MDAVtUPW5IwIY/edit#gid=927345496&fvid=162673764 and pick the `type` column for everything annotated as `controlled_term` is `nb:Age`
- take the script to make new json files: https://github.com/neurobagel/bulk_annotations/blob/a53a17b8df051ef38849cfa47109c496fc2aec64/process_annotation_to_dict.py and add logic to provide Transformations
- pull in the updated
