### ISSUE TITLE
Dataset .jsonld files missing portalURI for datasets

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bulk_annotations#20]
- [x] Update https://github.com/neurobagel/bulk_annotations/blob/main/run_bagel_cli.sh to provide `--portal` upon running `bagel pheno`

Alternatively: could maybe be resolved with an `INSERT` query?

**Comment by surchs** [comment]
Sorry for just dumping here, the missing dataset name should be a separate issue. But we should be able to get it easily via the cli during the bids step when we have access to the full bids dataset. So maybe rerunning the bulk script after teaching the cli to read the dataset name would be the fastest way to go here
