### ISSUE TITLE
Create process to automatically process annotated BIDS datalad dataset into graph ready file

### ISSUE THREAD

**Issue by surchs** [neurobagel/bulk_annotations#4]
Given a list of Neurobagel annotated BIDS datasets that are also tracked by datalad, I want to give some process the datalad id of a dataset (or list of several), so that the process then creates the harmonized, graph ready .jsonld representation of the dataset that I can upload to a graph.

Some tasks (clarify in spec):
  - [x] get the BIDS portion of a dataset, parse it
  - [x] given annotation (.json), process data into jsonld. Combine with BIDS
  - [x] store combined .jsonld for future upload

also see https://github.com/con/job/issues/1 for a possible place / process where we could store these data dictionaries

We now have https://github.com/OpenNeuroDatasets-JSONLD/ as a datalad enabled superdataset of OpenNeuro datasets with our augmented annotations 🎉 

current plan: 

- [x] clone a dataset from https://github.com/OpenNeuroDatasets-JSONLD/ using `git` or `datalad`
- [x] run `bagel pheno` on it, assuming file names
- [x] run `bagel bids` on it again, completing the work
- [x] check that the `bagel.jsonld` file was made

**Comment by surchs** [comment]
Maybe this would be more appropriately stored with https://github.com/neurobagel/bagel-cli ?
@alyssadai wdyt?

**Comment by alyssadai** [comment]
@surchs hmm, I'm not sure. Like we discussed in our chat today, I don't sense that this would actually entail a major change to the `bagel-cli` codebase itself (?), but would probably involve constructing a new (shell?) script that probably repeatedly calls the CLI somehow. In which case, I think it's okay to track it in the current repo.

The alternative I guess would be to update the CLI to be able to parse multiple datasets at once? Not sure if we want to pursue that direction.

**Comment by surchs** [comment]
OK, let's keep it all in this repo for now!

**Comment by surchs** [comment]
Blocked by #3

**Comment by jarmoza** [comment]
Blocked by https://github.com/neurobagel/bagel-cli/issues/141

**Comment by surchs** [comment]
I will use https://github.com/OpenNeuroDatasets-JSONLD/ds003770/blob/master/participants.json as a testing dataset

**Comment by surchs** [comment]
Blocked by https://github.com/neurobagel/bagel-cli/issues/141 and https://github.com/neurobagel/bagel-cli/issues/149

**Comment by alyssadai** [comment]
Hey @surchs, I took a quick look at the subtasks and think they are all completed with #19 and #22.

Would you agree this is good to close?
