### ISSUE TITLE
Create a summary file to bulk annotate OpenNeuro pheno data: part 2 include levels

### ISSUE THREAD

**Issue by Remi-Gau** [neurobagel/bulk_annotations#8]
Follow up on #1 

We need a tsv that for a given list of OpenNeuro / datalad BIDS datasets
- lists each column of participants.tsv (with description from .json if available)
- lists the discrete values
- has a column where we can enter controlled term IRIs to signify that the col/val combo should be mapped to this term

Tasks:
  - [x] Create a script that can get and process a number of ON datasets
  - [x] Get as little data as possible (e.g. use datalad)
  - [x] Find the `participants.tsv` file in each dataset (and `participants.json` if available)
  - [x] Do some basic filtering on these files to exclude bad data / data we don't like
    - [x] we should not annotate the levels of continuous data 
  - [x] identify discrete variables and show unique elements
  - [x] create a spreadsheet that allows us to manually annotate:
    - dataset ID
    - nb rows in participants.tsv
    - column name 
    - column description
    - data type of each column (int, float, datetime, euro, range...)
    - nb levels in that column
    - is_row
    - controlled_term
    - units
    - term_url

This could probably be tackled in separate issue / PR.

The idea is that a human annotator can go and add controlled term mappings in the `controlled_term` column.
The idea of `is_row` is to allow us to say what a specific column in the `participants.tsv` file is "about", before we then
go and look at each unique value inside of this column (provided the column is about a discrete variable) and annotate each value as well.

Adding an example

| dataset  | 	nb_rows | 	column | 	value | 	type | 	nb_levels | 	is_row | 	description | 	controlled_term | 	units | 	term_url |
| -  | 	- | 	- | 	- | 	- | 	- | 	- | 	- | 	- | 	- | 	- |
| ds000001  | 	16 | 	participant_id | 	n/a | 	object | 	16 | 	True | 	n/a | 	nb:ParticipantID | 	n/a | 	n/a |
| ds000001  | 	16 | 	sex | 	n/a | 	object | 	3 | 	True | 	n/a | 	nb:Sex | 	n/a | 	n/a |
| ds000001  | 	16 | 	age | 	n/a | 	int64 | 	8 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	diagnosis | 	n/a | 	object | 	4 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	diagnosis | 	BIPOLAR | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	diagnosis | 	ADHD | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	diagnosis | 	CONTROL | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	diagnosis | 	SCHZ | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	age | 	n/a | 	int64 | 	30 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	gender | 	n/a | 	object | 	2 | 	True | 	n/a | 	nb:Sex | 	n/a | 	n/a |
| ds000030  | 	272 | 	bart | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	bht | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	dwi | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	pamenc | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	pamret | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	rest | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	scap | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	stopsignal | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	T1w | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	taskswitch | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	ScannerSerialNumber | 	n/a | 	float64 | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	ghost_NoGhost | 	n/a | 	object | 	2 | 	True | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	ghost_NoGhost | 	No_ghost | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |
| ds000030  | 	272 | 	ghost_NoGhost | 	ghost | 	n/a | 	0 | 	False | 	n/a | 	n/a | 	n/a | 	n/a |

**Comment by Remi-Gau** [comment]
In the example I above we would actually want to list the levels for things like sex, gender. No?

**Comment by Remi-Gau** [comment]
@surchs

**Comment by surchs** [comment]
yes, exactly. The only case where we would limit this to the column_row (i.e. `is_row == True`) would be for columns where we are pretty sure it's a continuous variable (like age). Everything that looks moderately discrete should have its values listed under the column_row

**Comment by Remi-Gau** [comment]
Okidoki.

Get ready for a PR with a lot of lines changes all of them in a single tsv file!
